src/compare_command.sh: add compare command
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

diff --git a/cli b/cli
--- a/cli
+++ b/cli
@@ -34,7 +34,8 @@ cli_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Extract subregions from a coreboot binary\n" "extract"
+  printf "  %s   Extract subregions from a firmware binary\n" "extract"
+  printf "  %s   Compare two binaries\n" "compare"
   echo
 
   # :command.long_usage
@@ -55,11 +56,11 @@ cli_usage() {
 # :command.usage
 cli_extract_usage() {
   if [[ -n $long_usage ]]; then
-    printf "cli extract - Extract subregions from a coreboot binary\n"
+    printf "cli extract - Extract subregions from a firmware binary\n"
     echo
 
   else
-    printf "cli extract - Extract subregions from a coreboot binary\n"
+    printf "cli extract - Extract subregions from a firmware binary\n"
     echo
 
   fi
@@ -97,6 +98,51 @@ cli_extract_usage() {
     # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  cli extract coreboot.rom\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cli_compare_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "cli compare - Compare two binaries\n"
+    echo
+
+  else
+    printf "cli compare - Compare two binaries\n"
+    echo
+
+  fi
+
+  printf "Alias: c\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  cli compare ROM1 ROM2\n"
+  printf "  cli compare --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "ROM1"
+    printf "    First ROM to compare\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "ROM2"
+    printf "    Second ROM to compare\n"
     echo
 
   fi
@@ -174,79 +220,132 @@ inspect_args() {
   fi
 }
 
+# :command.user_lib
+# src/lib/extract.sh
+
+is_ifd_rom() {
+	filetype=$(file -b $1)
+	[[ $filetype = "Intel serial flash for PCH ROM" ]]
+}
+
+is_fmap_rom() {
+	grep -obUaP "__FMAP__" $1 &> /dev/null
+	[[ $? = 0 ]]
+}
+
+is_cbfs_rom() {
+	cbfstool $1 print &> /dev/null
+	[[ $? = 0 ]]
+}
+
+rom_extract() {
+	set +e # bleh
+
+	rom_file=$1
+	output_dir=$2
+	if [ ! -f $rom_file ]; then
+		echo "File $rom_file does not exist. Please input a valid ROM file path."
+		return 1
+	fi
+	if [ -z "$output_dir" ]; then
+		output_dir=$rom_file.extracted
+	fi
+	mkdir -p $output_dir
+	if is_ifd_rom $rom_file; then
+		echo "ROM contains an Intel Flash Descriptor"
+		mkdir -p $output_dir/regions/ifd
+		pushd $output_dir/regions/ifd > /dev/null
+		ifdtool -x $rom_file &> /dev/null
+		ls | fmt -s | sed "s/^/[IFD] /"
+		popd > /dev/null
+		echo
+	fi
+	if is_fmap_rom $rom_file; then
+		echo "ROM contains a coreboot FMAP"
+		regions=$(cbfstool novacustom_v56x_mtl_v0.9.0.rom layout -w \
+		    | grep \' \
+		    | cut -d \' -f 2 \
+		    | grep -v -e "SI_ALL" -e "SI_BIOS" -e "RW_SECTION_A" -e "RW_SECTION_B" -e "RW_MISC" -e "UNIFIED_MRC_CACHE" -e "RW_SHARED" -e "WP_RO" -e "RO_SECTION"
+		    )
+		mkdir -p $output_dir/regions/fmap
+		pushd $output_dir/regions/fmap > /dev/null
+		for region in $regions; do
+			echo "[FMAP] $region.bin"
+			cbfstool $rom_file read -r $region -f $region.bin
+			if is_cbfs_rom $region.bin; then
+				echo "Region contains a CBFS"
+				mkdir -p $region.cbfs
+				cbfs_files=$(cbfstool $rom_file print -r $region | cut -d ' ' -f 1 | tail -n +3 | grep -v "(empty)")
+				pushd $region.cbfs > /dev/null
+				for file in $cbfs_files; do
+					echo "  [CBFS] $file"
+					cbfstool $rom_file extract -r $region -f $(echo $file | tr \/ -) -n $file -m x86 &> /dev/null # TODO FIXME etc
+				done
+				popd > /dev/null
+			fi
+		done
+		popd > /dev/null
+		echo
+	fi
+}
+
 # :command.command_functions
 # :command.function
 cli_extract_command() {
   # src/extract_command.sh
-  inspect_args
-
   ROM_FILE=$(realpath "${args[rom]}")
   OUTPUT_DIR="${args[output]}"
 
-  set +e # bleh
+  rom_extract $ROM_FILE $OUTPUT_DIR
 
-  # Checks if a ROM is an Intel-style binary with flash descriptor.
-  is_ifd_rom() {
-  	filetype=$(file -b $1)
-  	[[ $filetype = "Intel serial flash for PCH ROM" ]]
-  }
+}
 
-  # Checks if a ROM has a coreboot FMAP flash region map.
-  is_fmap_rom() {
-  	grep -obUaP "__FMAP__" $1 &> /dev/null
-  	[[ $? = 0 ]]
-  }
+# :command.function
+cli_compare_command() {
+  # src/compare_command.sh
+  ROM1_FILE=$(realpath "${args[rom1]}")
+  ROM2_FILE=$(realpath "${args[rom2]}")
+  OUTPUT_DIR="${args[output]}"
 
-  is_cbfs_rom() {
-  	cbfstool $1 print &> /dev/null
-  	[[ $? = 0 ]]
-  }
+  WORKDIR=/tmp/romscope
 
-  main() {
-  	if [ ! -f $ROM_FILE ]; then
-  		echo "File $ROM_FILE does not exist. Please input a valid ROM file path."
-  		return 1
+  main () {
+  	if [ -e $WORKDIR ]; then
+  		rm -r $WORKDIR
   	fi
+
+  	echo "Extracting file $ROM1_FILE"
+  	mkdir -p $WORKDIR/a
+  	rom_extract $ROM1_FILE $WORKDIR/a > /dev/null
+  	pushd $WORKDIR/a > /dev/null
+  	find regions -type f -exec printf '%s\n' {} + > manifest
+  	popd > /dev/null
+
+  	echo "Extracting file $ROM2_FILE"
+  	mkdir -p $WORKDIR/b
+  	rom_extract $ROM2_FILE $WORKDIR/b > /dev/null
+  	pushd $WORKDIR/b > /dev/null
+  	find regions -type f -exec printf '%s\n' {} + > manifest
+  	popd > /dev/null
+
+  	pushd $WORKDIR > /dev/null
+  	files=$(cat a/manifest \
+  		| grep -v -e "regions/fmap/FW_MAIN_A.bin" -e "regions/fmap/FW_MAIN_B.bin" -e "regions/fmap/COREBOOT.bin" -e "regions/fmap/VBLOCK_A.bin" -e "regions/fmap/VBLOCK_B.bin" -e "regions/ifd/flashregion" \
+  		)
+  	for file in $files; do
+  		echo "Generating report for $file"
+  		diffoscope a/$file b/$file --html $(echo $file | tr \/ -).html &> /dev/null
+  	done
+  	popd > /dev/null
+
   	if [ -z "$OUTPUT_DIR" ]; then
-  		OUTPUT_DIR=$ROM_FILE.extracted
+  	 	OUTPUT_DIR="report"
   	fi
   	mkdir -p $OUTPUT_DIR
-  	if is_ifd_rom $ROM_FILE; then
-  		echo "ROM contains an Intel Flash Descriptor"
-  		mkdir -p $OUTPUT_DIR/regions/ifd
-  		pushd $OUTPUT_DIR/regions/ifd > /dev/null
-  		ifdtool -x $ROM_FILE &> /dev/null
-  		ls | fmt -s | sed "s/^/[IFD] /"
-  		popd > /dev/null
-  		echo
-  	fi
-  	if is_fmap_rom $ROM_FILE; then
-  		echo "ROM contains a coreboot FMAP"
-  		regions=$(cbfstool novacustom_v56x_mtl_v0.9.0.rom layout -w \
-  		    | grep \' \
-  		    | cut -d \' -f 2 \
-  		    | grep -v -e "SI_ALL" -e "SI_BIOS" -e "RW_SECTION_A" -e "RW_SECTION_B" -e "RW_MISC" -e "UNIFIED_MRC_CACHE" -e "RW_SHARED" -e "WP_RO" -e "RO_SECTION"
-  		    )
-  		mkdir -p $OUTPUT_DIR/regions/fmap
-  		pushd $OUTPUT_DIR/regions/fmap > /dev/null
-  		for region in $regions; do
-  			echo "[FMAP] $region.bin"
-  			cbfstool $ROM_FILE read -r $region -f $region.bin
-  			if is_cbfs_rom $region.bin; then
-  				echo "Region contains a CBFS"
-  				mkdir -p $region.cbfs
-  				cbfs_files=$(cbfstool $ROM_FILE print -r $region | cut -d ' ' -f 1 | tail -n +3 | grep -v "(empty)")
-  				pushd $region.cbfs > /dev/null
-  				for file in $cbfs_files; do
-  					echo "  [CBFS] $file"
-  					cbfstool $ROM_FILE extract -r $region -f $(echo $file | tr \/ -) -n $file -m x86 &> /dev/null # TODO FIXME etc
-  				done
-  				popd > /dev/null
-  			fi
-  		done
-  		popd > /dev/null
-  		echo
-  	fi
+  	cp $WORKDIR/*.html $OUTPUT_DIR/
+  	echo "Report placed in folder: '$OUTPUT_DIR'"
+
+  	rm -r $WORKDIR
   }
 
   main
@@ -293,6 +392,14 @@ parse_requirements() {
     exit 1
   fi
 
+  if command -v ifdtool >/dev/null 2>&1; then
+    deps['diffoscope']="$(command -v ifdtool | head -n1)"
+  else
+    printf "missing dependency: diffoscope\n" >&2
+    printf "%s\n" "You can install from your distribution's package repositories or build from source code: https://diffoscope.org/\n" >&2
+    exit 1
+  fi
+
   # :command.command_filter
   action=${1:-}
 
@@ -303,6 +410,13 @@ parse_requirements() {
       action="extract"
       shift
       cli_extract_parse_requirements "$@"
+      shift $#
+      ;;
+
+    compare | c)
+      action="compare"
+      shift
+      cli_compare_parse_requirements "$@"
       shift $#
       ;;
 
@@ -402,6 +516,70 @@ cli_extract_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+cli_compare_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        cli_compare_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="compare"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['rom1']+x} ]]; then
+          args['rom1']=$1
+          shift
+        # :argument.case
+        elif [[ -z ${args['rom2']+x} ]]; then
+          args['rom2']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['rom1']+x} ]]; then
+    printf "missing required argument: ROM1\nusage: cli compare ROM1 ROM2\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['rom2']+x} ]]; then
+    printf "missing required argument: ROM2\nusage: cli compare ROM1 ROM2\n" >&2
+    exit 1
+  fi
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -422,6 +600,7 @@ run() {
 
   case "$action" in
     "extract") cli_extract_command ;;
+    "compare") cli_compare_command ;;
   esac
 }
 
