Rename to romscope
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

diff --git a/romscope b/romscope
--- a/romscope
+++ b/romscope
@@ -16,21 +16,21 @@ version_command() {
 }
 
 # :command.usage
-cli_usage() {
+romscope_usage() {
   if [[ -n $long_usage ]]; then
-    printf "cli - Sample application\n"
+    printf "romscope - A tool for comparing firmware binaries\n"
     echo
 
   else
-    printf "cli - Sample application\n"
+    printf "romscope - A tool for comparing firmware binaries\n"
     echo
 
   fi
 
   printf "%s\n" "Usage:"
-  printf "  cli COMMAND\n"
-  printf "  cli [COMMAND] --help | -h\n"
-  printf "  cli --version | -v\n"
+  printf "  romscope COMMAND\n"
+  printf "  romscope [COMMAND] --help | -h\n"
+  printf "  romscope --version | -v\n"
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
@@ -54,13 +54,13 @@ cli_usage() {
 }
 
 # :command.usage
-cli_extract_usage() {
+romscope_extract_usage() {
   if [[ -n $long_usage ]]; then
-    printf "cli extract - Extract subregions from a firmware binary\n"
+    printf "romscope extract - Extract subregions from a firmware binary\n"
     echo
 
   else
-    printf "cli extract - Extract subregions from a firmware binary\n"
+    printf "romscope extract - Extract subregions from a firmware binary\n"
     echo
 
   fi
@@ -69,8 +69,8 @@ cli_extract_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  cli extract ROM [OUTPUT]\n"
-  printf "  cli extract --help | -h\n"
+  printf "  romscope extract ROM [OUTPUT]\n"
+  printf "  romscope extract --help | -h\n"
   echo
 
   # :command.long_usage
@@ -104,13 +104,13 @@ cli_extract_usage() {
 }
 
 # :command.usage
-cli_compare_usage() {
+romscope_compare_usage() {
   if [[ -n $long_usage ]]; then
-    printf "cli compare - Compare two binaries\n"
+    printf "romscope compare - Compare two binaries\n"
     echo
 
   else
-    printf "cli compare - Compare two binaries\n"
+    printf "romscope compare - Compare two binaries\n"
     echo
 
   fi
@@ -119,8 +119,8 @@ cli_compare_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  cli compare ROM1 ROM2\n"
-  printf "  cli compare --help | -h\n"
+  printf "  romscope compare ROM1 ROM2 [OUTPUT]\n"
+  printf "  romscope compare --help | -h\n"
   echo
 
   # :command.long_usage
@@ -143,6 +143,11 @@ cli_compare_usage() {
     # :argument.usage
     printf "  %s\n" "ROM2"
     printf "    Second ROM to compare\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "OUTPUT"
+    printf "    Directory to put report to (default: report)\n"
     echo
 
   fi
@@ -295,7 +300,7 @@ rom_extract() {
 
 # :command.command_functions
 # :command.function
-cli_extract_command() {
+romscope_extract_command() {
   # src/extract_command.sh
   # SPDX-FileCopyrightText: 2024 3mdeb Sp. z o. o.
   #
@@ -309,7 +314,7 @@ cli_extract_command() {
 }
 
 # :command.function
-cli_compare_command() {
+romscope_compare_command() {
   # src/compare_command.sh
   # SPDX-FileCopyrightText: 2024 3mdeb Sp. z o. o.
   #
@@ -376,7 +381,7 @@ parse_requirements() {
 
       --help | -h)
         long_usage=yes
-        cli_usage
+        romscope_usage
         exit
         ;;
 
@@ -421,20 +426,20 @@ parse_requirements() {
     extract | e)
       action="extract"
       shift
-      cli_extract_parse_requirements "$@"
+      romscope_extract_parse_requirements "$@"
       shift $#
       ;;
 
     compare | c)
       action="compare"
       shift
-      cli_compare_parse_requirements "$@"
+      romscope_compare_parse_requirements "$@"
       shift $#
       ;;
 
     # :command.command_fallback
     "")
-      cli_usage >&2
+      romscope_usage >&2
       exit 1
       ;;
 
@@ -469,13 +474,13 @@ parse_requirements() {
 }
 
 # :command.parse_requirements
-cli_extract_parse_requirements() {
+romscope_extract_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        cli_extract_usage
+        romscope_extract_usage
         exit
         ;;
 
@@ -522,20 +527,20 @@ cli_extract_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['rom']+x} ]]; then
-    printf "missing required argument: ROM\nusage: cli extract ROM [OUTPUT]\n" >&2
+    printf "missing required argument: ROM\nusage: romscope extract ROM [OUTPUT]\n" >&2
     exit 1
   fi
 
 }
 
 # :command.parse_requirements
-cli_compare_parse_requirements() {
+romscope_compare_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        cli_compare_usage
+        romscope_compare_usage
         exit
         ;;
 
@@ -570,6 +575,10 @@ cli_compare_parse_requirements() {
         elif [[ -z ${args['rom2']+x} ]]; then
           args['rom2']=$1
           shift
+        # :argument.case
+        elif [[ -z ${args['output']+x} ]]; then
+          args['output']=$1
+          shift
         else
           printf "invalid argument: %s\n" "$key" >&2
           exit 1
@@ -582,11 +591,11 @@ cli_compare_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['rom1']+x} ]]; then
-    printf "missing required argument: ROM1\nusage: cli compare ROM1 ROM2\n" >&2
+    printf "missing required argument: ROM1\nusage: romscope compare ROM1 ROM2 [OUTPUT]\n" >&2
     exit 1
   fi
   if [[ -z ${args['rom2']+x} ]]; then
-    printf "missing required argument: ROM2\nusage: cli compare ROM1 ROM2\n" >&2
+    printf "missing required argument: ROM2\nusage: romscope compare ROM1 ROM2 [OUTPUT]\n" >&2
     exit 1
   fi
 
@@ -611,8 +620,8 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
-    "extract") cli_extract_command ;;
-    "compare") cli_compare_command ;;
+    "extract") romscope_extract_command ;;
+    "compare") romscope_compare_command ;;
   esac
 }
 
